### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by 4hilton** [pbauerochse/youtrack-worklog-viewer#29] opened 2018-06-12 19:11 UTC
I have tried to connect several times following the Wiki instructions. Please help. I am using the trial version cloud version of YouTrack is that an issue?

**Comment by pbauerochse** [comment] 2018-06-19 18:39
I don't think it matters, that you are using the trial version. There seems to be an issue with the 2018.2 version of YouTrack (see #27) and I assume, that the cloud version is already 2018.2, can you confirm?

If it indeed is a 2018.2 version please hold on. I'm already working on making the Worklog Viewer work with it.

**Comment by pbauerochse** [comment] 2018-07-03 12:39
Closing this as a duplicate of #27

**Closed by pbauerochse** 2018-07-03 12:39 UTC
